version: '3'

networks:
  clipping:

services:
  mongo:
    image: mongo
    ports:
      - 27017:27017
    networks:
      - clipping
  
  rabbitmq:
    image: rabbitmq:3.9-management
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - clipping