version: '3'

networks:
  bootcamp_ici:

services:
  newsconsumerproxy:
    build: ./NewsConsumer/Proxy
    ports:
      - 80:80
    expose:
      - "80"
    networks:
      - bootcamp_ici
    environment:
      - NEWSCONSUMERAPI_ADDRESS=http://newsconsumerapi
    depends_on:
      - newsconsumerapi

  newsconsumerapi:
    build: ./NewsConsumer/API
    networks:
      - bootcamp_ici
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_NewsConsumerDatabase__DatabaseName=NewsConsumer
      - ASPNETCORE_NewsConsumerDatabase__ConnectionString=mongodb://mongo:27017
    depends_on:
      - mongo
  
  analyzecommentsproxy:
    build: ./AnalyzeComments/Proxy
    ports:
      - 81:81
    networks:
      - bootcamp_ici
    environment:
      - ANALYZECOMMENTSAPI_ADDRESS=http://analyzecommentsapi
    depends_on:
      - analyzecommentsapi

  analyzecommentsapi:
    build: ./AnalyzeComments/API
    networks:
      - bootcamp_ici
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_ResultAnalyzeDatabase__DatabaseName=AnalyzeComments
      - ASPNETCORE_ResultAnalyzeDatabase__ConnectionString=mongodb://mongo:27017
      - ASPNETCORE_NewsConsumerAddress=http://newsconsumerapi/api/GetComments
    depends_on:
      - newsconsumerapi
      - mongo

  mongo:
    image: mongo
    ports:
      - 27017:27017
    networks:
      - bootcamp_ici