version: '3'

networks:
  bootcamp_ici:

services:
  newsconsumerapi:
    build: ./NewsConsumerAPI
    ports:
      - 7003:80
    networks:
      - bootcamp_ici
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_NewsConsumerDatabase__ConnectionString=mongodb://mongo:27017
      - ASPNETCORE_NewsConsumerDatabase__DatabaseName=NewsConsumer
    depends_on:
      - mongo

  mongo:
    image: mongo
    ports:
      - 27017:27017
    networks:
      - bootcamp_ici
  
  rabbitmq:
    image: rabbitmq:3.9-management
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - bootcamp_ici