version: '3'

networks:
  bootcamp_ici:

services:
  newsconsumerproxy:
    build: ./NewsConsumer/Proxy
    ports:
      - 80:80
    networks:
      - bootcamp_ici
    environment:
      - NEWSCONSUMERAPI_ADDRESS=http://newsconsumerapi
    depends_on:
      - newsconsumerapi

  newsconsumerapi:
    build: ./NewsConsumer/API
    networks:
      - bootcamp_ici
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_NewsConsumerDatabase__DatabaseName=NewsConsumer
      - ASPNETCORE_NewsConsumerDatabase__ConnectionString=mongodb://mongo:27017
    depends_on:
      - mongo

  mongo:
    image: mongo
    ports:
      - 27017:27017
    networks:
      - bootcamp_ici